
export const LANG = {
  pl:{
    tagline:"Powiedz, dokąd chcesz jechać. Voyana porówna całą podróż.",
    prompt:"Opisz podróż",
    placeholder:"Np. Turcja na 10 dni we wrześniu",
    analyse:"Zrozum zapytanie",
    compare:"Znajdź najlepszą podróż",
    start:"Miasto startowe",
    destination:"Cel",
    depart:"Data wylotu",
    ret:"Data powrotu",
    adults:"Dorośli",
    cabin:"Klasa",
    loading:"Voyana porównuje lotniska i analizuje loty…",
    parsed:"Rozpoznane dane",
    days:"Długość",
    month:"Miesiąc",
    budget:"Budżet",
    notProvided:"Nie podano",
    found:"Znaleziono",
    offers:"ofert",
    error:"Błąd",
    noOffers:"Brak ofert dla tych parametrów.",
    tap:"Kliknij, aby zobaczyć szczegóły",
    test:"Tryb testowy: dane mogą nie odpowiadać pełnemu rynkowi."
  },
  en:{
    tagline:"Tell us where you want to go. Voyana compares the whole journey.",
    prompt:"Describe your trip",
    placeholder:"Example: Turkey for 10 days in September",
    analyse:"Understand my request",
    compare:"Find my best journey",
    start:"Starting city",
    destination:"Destination",
    depart:"Departure date",
    ret:"Return date",
    adults:"Adults",
    cabin:"Cabin class",
    loading:"Voyana is comparing airports and analysing flights…",
    parsed:"Understood details",
    days:"Length",
    month:"Month",
    budget:"Budget",
    notProvided:"Not provided",
    found:"Found",
    offers:"offers",
    error:"Error",
    noOffers:"No offers found.",
    tap:"Tap to view details",
    test:"Test mode: results may not reflect the full live market."
  },
  es:{
    tagline:"Dinos a dónde quieres ir. Voyana compara todo el viaje.",
    prompt:"Describe tu viaje",
    placeholder:"Ejemplo: Turquía por 10 días en septiembre",
    analyse:"Entender mi solicitud",
    compare:"Encontrar el mejor viaje",
    start:"Ciudad de salida",
    destination:"Destino",
    depart:"Fecha de salida",
    ret:"Fecha de regreso",
    adults:"Adultos",
    cabin:"Clase",
    loading:"Voyana está comparando aeropuertos y vuelos…",
    parsed:"Datos reconocidos",
    days:"Duración",
    month:"Mes",
    budget:"Presupuesto",
    notProvided:"No indicado",
    found:"Encontradas",
    offers:"ofertas",
    error:"Error",
    noOffers:"No se encontraron ofertas.",
    tap:"Pulsa para ver detalles",
    test:"Modo de prueba: los resultados pueden no reflejar el mercado completo."
  }
};
